# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_generate_sobol_set <- function(N, dim, scramble) {
    .Call(`_spacefillr_rcpp_generate_sobol_set`, N, dim, scramble)
}

rcpp_generate_sobol_owen_set <- function(N, dim, scramble) {
    .Call(`_spacefillr_rcpp_generate_sobol_owen_set`, N, dim, scramble)
}

rcpp_generate_sobol_owen_single <- function(i, dim, scramble) {
    .Call(`_spacefillr_rcpp_generate_sobol_owen_single`, i, dim, scramble)
}

rcpp_generate_halton_faure_set <- function(N, dim) {
    .Call(`_spacefillr_rcpp_generate_halton_faure_set`, N, dim)
}

rcpp_generate_halton_random_set <- function(N, dim, seed) {
    .Call(`_spacefillr_rcpp_generate_halton_random_set`, N, dim, seed)
}

rcpp_generate_halton_faure_single <- function(i, dim) {
    .Call(`_spacefillr_rcpp_generate_halton_faure_single`, i, dim)
}

rcpp_generate_halton_random_single <- function(i, dim, seed) {
    .Call(`_spacefillr_rcpp_generate_halton_random_single`, i, dim, seed)
}

rcpp_generate_pj_set <- function(N, seed) {
    .Call(`_spacefillr_rcpp_generate_pj_set`, N, seed)
}

rcpp_generate_pmj_set <- function(N, seed) {
    .Call(`_spacefillr_rcpp_generate_pmj_set`, N, seed)
}

rcpp_generate_pmjbn_set <- function(N, seed) {
    .Call(`_spacefillr_rcpp_generate_pmjbn_set`, N, seed)
}

rcpp_generate_pmj02_set <- function(N, seed) {
    .Call(`_spacefillr_rcpp_generate_pmj02_set`, N, seed)
}

rcpp_generate_pmj02bn_set <- function(N, seed) {
    .Call(`_spacefillr_rcpp_generate_pmj02bn_set`, N, seed)
}

